"""empty message

Revision ID: 65a7b41e4978
Revises: 
Create Date: 2023-11-14 19:25:04.304751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a7b41e4978'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_summary', sa.String(length=200), nullable=True))
        batch_op.drop_column('completed')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.INTEGER(), nullable=True))
        batch_op.drop_column('content_summary')

    # ### end Alembic commands ###
